services:
  - type: web
    name: tech-inventory
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tech-inventory-db
          property: connectionString

databases:
  - name: tech-inventory-db
    plan: free
    databaseName: tech_inventory
    user: tech_inventory_user 