services:
  - type: web
    name: tech-gadget-inventory
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gadget-inventory-db
          property: connectionString

databases:
  - name: gadget-inventory-db
    databaseName: gadget_inventory
    user: gadget_inventory_user 