services:
  - type: web
    name: tech-gadget-inventory
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tech_gadget_inventory
          property: connectionString

databases:
  - name: tech_gadget_inventory
    databaseName: tech_gadget_inventory
    user: tech_gadget_admin
    plan: free 